// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAloAxtKCRozXKnTSwzJLUZODxWQjvU2VQ',
    appId: '1:8108991148:web:e7183cfbd79e08ebd2f509',
    messagingSenderId: '8108991148',
    projectId: 'jobs-finder-1aa95',
    authDomain: 'jobs-finder-1aa95.firebaseapp.com',
    storageBucket: 'jobs-finder-1aa95.appspot.com',
    measurementId: 'G-YFSRXBBWQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdyCOeMXKQ9DX47BHmFyvTGg5EwhjGyKs',
    appId: '1:8108991148:android:74b39d00c8556700d2f509',
    messagingSenderId: '8108991148',
    projectId: 'jobs-finder-1aa95',
    storageBucket: 'jobs-finder-1aa95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQNoyUUmnBiRAqznNOX5qvBUM7Z5Dvzl8',
    appId: '1:8108991148:ios:cc0284e7396250b3d2f509',
    messagingSenderId: '8108991148',
    projectId: 'jobs-finder-1aa95',
    storageBucket: 'jobs-finder-1aa95.appspot.com',
    iosBundleId: 'com.example.jobsfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQNoyUUmnBiRAqznNOX5qvBUM7Z5Dvzl8',
    appId: '1:8108991148:ios:cc0284e7396250b3d2f509',
    messagingSenderId: '8108991148',
    projectId: 'jobs-finder-1aa95',
    storageBucket: 'jobs-finder-1aa95.appspot.com',
    iosBundleId: 'com.example.jobsfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAloAxtKCRozXKnTSwzJLUZODxWQjvU2VQ',
    appId: '1:8108991148:web:eb4b8426ecbb2dfad2f509',
    messagingSenderId: '8108991148',
    projectId: 'jobs-finder-1aa95',
    authDomain: 'jobs-finder-1aa95.firebaseapp.com',
    storageBucket: 'jobs-finder-1aa95.appspot.com',
    measurementId: 'G-B1PHFYTSCZ',
  );
}
